### ISSUE TITLE
error parsing config file

### ISSUE THREAD

**Issue by masher1** [kasvith/hackerrank-dl#4]
Hey @kasvith. First of all thank you for creating this tool! I am attempting to extract data and I believe I did everything correctly and I am still getting an error message: `level=fatal msg="error parsing config file, yaml: line 6: could not find expected ':'"` Any idea how I could resolve it? You can email me at masher@syr.edu and I can send you a screenshot of my config file.

**Comment by kasvith** [comment]
I did not receive your email

**Comment by masher1** [comment]
Here is the file

**Comment by masher1** [comment]
Here is the file
[config - Copy.txt](https://github.com/kasvith/hackerrank-dl/files/5891550/config.-.Copy.txt)

**Comment by kasvith** [comment]
Ok i downloaded it, you may delete above comment @masher1

**Comment by kasvith** [comment]
use this for config. let me know when you copied the file so i can delete this comment
[config.-.Copy.txt](https://github.com/kasvith/hackerrank-dl/files/5891609/config.-.Copy.txt)

**Comment by kasvith** [comment]
Or simply adding two spaces like this will also work(proper yaml formatting as in README)
[config.-.Copy.txt](https://github.com/kasvith/hackerrank-dl/files/5891619/config.-.Copy.txt)

**Comment by masher1** [comment]
@kasvith Downloaded them.

**Comment by kasvith** [comment]
Cool, i will remove comments. If anything wrong send me an email to alankasun@gmail.com

**Comment by kasvith** [comment]
Close the issue if its resolved

**Comment by LearningLeopard** [comment]
I am also getting the same error. Could you tell me how to resolve this?

**Comment by kasvith** [comment]
@ChiatanyaChakka you need to properly format the yaml file. That was the issue he had

**Comment by LearningLeopard** [comment]
Can you verify mine too? Ill send you the config file via email

**Comment by kasvith** [comment]
Sure

**Comment by LearningLeopard** [comment]
I have sent the file. Please verify and revert as soon as possible. Thanks!

**Comment by kasvith** [comment]
@ChiatanyaChakka your YAML file had an issue.
I've sent the corrected version. 

Please be kind enough to use a YAML validator in your IDE
